version: '3'
services:
  redis-server:
    image: 'redis'
    networks:
      - app-network

  node-app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - redis-server
    networks:
      - app-network

  varnish:
    image: varnish:stable
    ports:
      - "8082:80"  # Varnish écoutera sur le port 8082
    depends_on:
      - node-app
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
